export type Token = {
  id: string;
  fileName: string;
  name: string;
};

export const tokens: Token[] = [
  { id: '1inch', fileName: '1INCH', name: '1inch' },
  { id: 'aave', fileName: 'AAVE', name: 'Aave' },
  { id: 'ada', fileName: 'ADA', name: 'Cardano' },
  { id: 'algo', fileName: 'ALGO', name: 'Algorand' },
  { id: 'apt', fileName: 'APT', name: 'Aptos' },
  { id: 'arb', fileName: 'ARB', name: 'Arbitrum' },
  { id: 'atom', fileName: 'ATOM', name: 'Cosmos' },
  { id: 'avax', fileName: 'AVAX', name: 'Avalanche' },
  { id: 'axs', fileName: 'AXS', name: 'Axie Infinity' },
  { id: 'bch', fileName: 'BCH', name: 'Bitcoin Cash' },
  { id: 'bnb', fileName: 'BNB', name: 'BNB' },
  { id: 'btc', fileName: 'BTC', name: 'Bitcoin' },
  { id: 'cfx', fileName: 'CFX', name: 'Conflux' },
  { id: 'crv', fileName: 'CRV', name: 'Curve DAO' },
  { id: 'doge', fileName: 'DOGE', name: 'Dogecoin' },
  { id: 'dot', fileName: 'DOT', name: 'Polkadot' },
  { id: 'egld', fileName: 'EGLD', name: 'MultiversX' },
  { id: 'enj', fileName: 'ENJ', name: 'Enjin Coin' },
  { id: 'eos', fileName: 'EOS', name: 'EOS' },
  { id: 'etc', fileName: 'ETC', name: 'Ethereum Classic' },
  { id: 'eth', fileName: 'ETH', name: 'Ethereum' },
  { id: 'fet', fileName: 'FET', name: 'Fetch.ai' },
  { id: 'fil', fileName: 'FIL', name: 'Filecoin' },
  { id: 'flow', fileName: 'FLOW', name: 'Flow' },
  { id: 'ftm', fileName: 'FTM', name: 'Fantom' },
  { id: 'gala', fileName: 'GALA', name: 'Gala' },
  { id: 'grt', fileName: 'GRT', name: 'The Graph' },
  { id: 'hbar', fileName: 'HBAR', name: 'Hedera' },
  { id: 'icp', fileName: 'ICP', name: 'Internet Computer' },
  { id: 'imx', fileName: 'IMX', name: 'Immutable' },
  { id: 'inj', fileName: 'INJ', name: 'Injective' },
  { id: 'jasmy', fileName: 'JASMY', name: 'JasmyCoin' },
  { id: 'kava', fileName: 'KAVA', name: 'Kava' },
  { id: 'kcs', fileName: 'KCS', name: 'KuCoin Token' },
  { id: 'link', fileName: 'LINK', name: 'Chainlink' },
  { id: 'lrc', fileName: 'LRC', name: 'Loopring' },
  { id: 'ltc', fileName: 'LTC', name: 'Litecoin' },
  { id: 'luna', fileName: 'LUNA', name: 'Terra' },
  { id: 'mana', fileName: 'MANA', name: 'Decentraland' },
  { id: 'matic', fileName: 'MATIC', name: 'Polygon' },
  { id: 'mina', fileName: 'MINA', name: 'Mina' },
  { id: 'mkr', fileName: 'MKR', name: 'Maker' },
  { id: 'near', fileName: 'NEAR', name: 'NEAR Protocol' },
  { id: 'neo', fileName: 'NEO', name: 'NEO' },
  { id: 'ocean', fileName: 'OCEAN', name: 'Ocean Protocol' },
  { id: 'op', fileName: 'OP', name: 'Optimism' },
  { id: 'pepe', fileName: 'PEPE', name: 'Pepe' },
  { id: 'qnt', fileName: 'QNT', name: 'Quant' },
  { id: 'render', fileName: 'RENDER', name: 'Render' },
  { id: 'rndr', fileName: 'RNDR', name: 'Render Token' },
  { id: 'rune', fileName: 'RUNE', name: 'THORChain' },
  { id: 'sand', fileName: 'SAND', name: 'The Sandbox' },
  { id: 'sei', fileName: 'SEI', name: 'Sei' },
  { id: 'shib', fileName: 'SHIB', name: 'Shiba Inu' },
  { id: 'snx', fileName: 'SNX', name: 'Synthetix' },
  { id: 'sol', fileName: 'SOL', name: 'Solana' },
  { id: 'stx', fileName: 'STX', name: 'Stacks' },
  { id: 'sui', fileName: 'SUI', name: 'Sui' },
  { id: 'sushi', fileName: 'SUSHI', name: 'SushiSwap' },
  { id: 'theta', fileName: 'THETA', name: 'Theta Network' },
  { id: 'tia', fileName: 'TIA', name: 'Celestia' },
  { id: 'ton', fileName: 'TON', name: 'Toncoin' },
  { id: 'trx', fileName: 'TRX', name: 'TRON' },
  { id: 'uni', fileName: 'UNI', name: 'Uniswap' },
  { id: 'usdc', fileName: 'USDC', name: 'USD Coin' },
  { id: 'usdt', fileName: 'USDT', name: 'Tether' },
  { id: 'vet', fileName: 'VET', name: 'VeChain' },
  { id: 'wbtc', fileName: 'WBTC', name: 'Wrapped Bitcoin' },
  { id: 'wld', fileName: 'WLD', name: 'Worldcoin' },
  { id: 'xlm', fileName: 'XLM', name: 'Stellar' },
  { id: 'xmr', fileName: 'XMR', name: 'Monero' },
  { id: 'xrp', fileName: 'XRP', name: 'XRP' },
  { id: 'xtz', fileName: 'XTZ', name: 'Tezos' },
  { id: 'zec', fileName: 'ZEC', name: 'Zcash' },
  { id: 'zil', fileName: 'ZIL', name: 'Zilliqa' },
];
